version: "3"
services:
  app:
    build: .
    command: air
    stdin_open: true
    tty: true
    depends_on:
      - db
    # environment:
    ports:
      - 8000:8000
    volumes:
      - .:/app:delegated
  db:
    build: ./mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: company_board
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      # 初期データ投入
      - ./mysql/init:/docker-entrypoint-initdb.d
      # 永続化用DBボリューム
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      # ホストのbリューム:コンテナのボリューム
      - 3307:3306
volumes:
  mysqldata:
